name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.RELEEN_GITHUB_TOKEN }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Build
        run: go build -v ./...

      - name: Unit Tests
        run: |
          go test ./...
